import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { CalendarDays, Check, Download, FileArchive, Monitor, ShieldCheck, Tag, UserRound } from 'lucide-react';
import { ScreenshotGallery } from '@/components/software/screenshot-gallery';
import { programs } from '@/lib/mock-data';

export function generateStaticParams(){return programs.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=programs.find(x=>x.slug===slug);return p?{title:p.name,description:p.description,openGraph:{title:`${p.name} ${p.version}`,description:p.description}}:{};}
export default async function ProgramDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=programs.find(x=>x.slug===slug);if(!p)notFound();return <main className="page-shell detail-page"><div className="shell detail-hero"><div><p className="eyebrow">{p.category}</p><div className="detail-title"><span className="detail-icon">{p.name.slice(0,2).toUpperCase()}</span><div><h1>{p.name}</h1><p>{p.version} · {p.status}</p></div></div><p className="detail-lead">{p.longDescription}</p><div className="detail-actions"><button className="btn btn-primary btn-lg"><Download/> {p.type==='FREE'?'ดาวน์โหลด':'ซื้อ License'}</button>{p.type==='PAID'&&<strong>{p.price.toLocaleString('th-TH')} THB</strong>}</div></div><div className="detail-console"><span>TR-SYNTAX VERIFIED</span><ShieldCheck/><strong>SAFE BUILD</strong><small>ตรวจสอบไฟล์ก่อนเผยแพร่ทุกเวอร์ชัน</small></div></div>
    <section className="shell content-section"><h2 className="subheading">Screenshot Gallery</h2><ScreenshotGallery name={p.name}/><div className="detail-columns"><article><h2>ความสามารถหลัก</h2><ul className="check-list">{p.features.map(f=><li key={f}><Check/>{f}</li>)}</ul><h2>System Requirements</h2><ul className="plain-list">{p.requirements.map(r=><li key={r}>{r}</li>)}</ul></article><aside className="info-card"><h3>รายละเอียดโปรแกรม</h3>{[[Tag,'Version',p.version],[FileArchive,'File Size',p.fileSize],[Monitor,'Supported',p.platform],[CalendarDays,'Release Date',p.releaseDate],[CalendarDays,'Last Update',p.updatedAt],[UserRound,'Developer',p.developer]].map(([Icon,label,value])=><div className="info-row" key={String(label)}><Icon/><span><small>{String(label)}</small><strong>{String(value)}</strong></span></div>)}</aside></div>
      <div className="changelog"><p className="eyebrow">WHAT&apos;S NEW</p><h2>{p.version}</h2><ul>{p.changelog.map(c=><li key={c}><Check/>{c}</li>)}</ul></div><Link href="/software" className="back-link">← กลับไปโปรแกรมทั้งหมด</Link></section></main>}
